### ISSUE TITLE
Empty user

### ISSUE THREAD

**Issue by loranger** [H2CK/webtrees#53]
Hello, I try to setup webtrees using docker-compose.
Everything works fine database is created, and populated, but no user is created and I can't figure out why.

Could you help me, please ?

<details>
<summary>.env</summary>

```env
APP_NAME="webtrees"
APP_PROJECT=webtrees
APP_DOMAIN=webtrees.mydomain.com

MARIADB_RANDOM_ROOT_PASSWORD=true
MYSQL_DATABASE=webtrees
MYSQL_USER=app_user
MYSQL_PASSWORD=secret
TZ=Europe/Paris

# https://github.com/H2CK/webtrees#parameters
# UPDATE_ON_START=true
GROUP_ID=999
DISABLE_SSL=TRUE
PORT=80
PRETTYURLS="1"
BASE_URL="http://${APP_DOMAIN}"
DB_HOST="${APP_PROJECT}-mariadb"
DB_USER="${MYSQL_USER}"
DB_PASSWORD="${MYSQL_PASSWORD}"
# DB_PORT=
DB_NAME="${MYSQL_DATABASE}"
WT_ADMIN="loranger"
WT_ADMINPW="my_password"
WT_ADMINMAIL="loranger@free.fr"
```

</details>

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3'

services:

  webtrees:
    container_name: ${APP_PROJECT}-webtrees
    image: dtjs48jkt/webtrees:latest
    # volumes:
      # - ./datas:/var/www/html/data
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    labels:
      - "traefik.http.routers.${APP_PROJECT}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.services.${APP_PROJECT}-service.loadbalancer.server.port=80"

  mariadb:
    container_name: ${APP_PROJECT}-mariadb
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  adminer:
    container_name: ${APP_PROJECT}-adminer
    image: adminer:latest
    environment:
        ADMINER_DEFAULT_SERVER: ${DB_HOST}
        ADMINER_DESIGN: flat
    profiles:
      - adminer
    labels:
      - "traefik.http.routers.${APP_PROJECT}-adminer.rule=Host(`adminer.${APP_DOMAIN}`)"
      - "traefik.http.services.${APP_PROJECT}-adminer-service.loadbalancer.server.port=8080"

networks:
  default:
      name: web
```

</details>
