### ISSUE TITLE
Modules not loading. 

### ISSUE THREAD

**Issue by arsaboo** [H2CK/webtrees#54]
I have added a custom module under the modules_v4 folder, but it is not showing up anywhere (even under preferences). I am using the latest version (2.1.1) of Webtrees in docker and I am using the [descendants chart](https://github.com/magicsunday/webtrees-descendants-chart), which was updated to support the latest release. Here's my docker-compose file:
```
version: '3.0'

services:
  webtrees:
    image: dtjs48jkt/webtrees
    restart: unless-stopped
    container_name: webtrees
    ports:
      - 8079:8079
    environment:
      - DISABLE_SSL=TRUE
      - PORT=8079
    volumes:
      - /mnt/docker/containers/webtrees/data:/var/www/html/data
      - /mnt/docker/containers/webtrees/modules_v4:/var/www/html/modules_v4
      - /mnt/docker/containers/webtrees/media:/var/www/html/media
    networks:
      - my-network
  
  mysql:
    image: mysql:5.5
    restart: unless-stopped
    container_name: webtrees_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_DATABASE=webtrees
      - MYSQL_USER=webtrees
      - MYSQL_PASSWORD=PASSWORD
    networks:
      - my-network
    volumes:
      - /mnt/docker/containers/webtrees_mysql:/var/lib/mysql
networks:
  my-network:
```

Everything is working except for the custom modules. It does not even show up in modules:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/18319734/166451812-24499196-b504-44a3-9937-2c2a7b119edc.png">
